routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Route::resource('recipient', 'RecipientController');
Route::resource('special-offer', 'SpecialOfferController');
Route::resource('voucher-code', 'VoucherCodeController')->only(['index', 'show']);
Route::get('voucher-code/{voucher_code}/redeem', 'VoucherCodeController@redeem')->name('voucher-code.redeem');
Route::post('voucher-code/{voucher_code}/redeem', 'VoucherCodeController@processRedeem')->name('voucher-code.redeem');

app/SpecialOffer.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class SpecialOffer extends Model
{
    use Sluggable;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'validity',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'discount',
        'validity',
    ];

    /**
     * Get all recipients from the Special Offer
     *
     * @return \App\Recipient
     */
    public function recipients()
    {
        return $this->belongsToMany(
            Recipient::class,
            'voucher_codes',
            'special_offer_id',
            'recipient_id'
        );
    }
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ],
        ];
    }

    /**
     * Apply Name filter in model
     *
     * @param  \Illuminate\Database\Eloquent\Builde $query
     * @param  string                               $name
     *
     * @return \Illuminate\Database\Eloquent\Builde
     */
    public function scopeFilterName($query, $name)
    {
        return $query->where('name', 'like', '%'.$name.'%');
    }

    /**
     * Apply Name filter in model
     *
     * @param  \Illuminate\Database\Eloquent\Builde $query
     * @param  integer                              $name
     *
     * @return \Illuminate\Database\Eloquent\Builde
     */
    public function scopeFilterDiscountGreaterThan($query, $discount)
    {
        return $query->where('discount', '>=', $discount);
    }
}

app/Http/Controllers/SpecialOfferController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SpecialOfferRequest;
use App\Repositories\SpecialOfferRepositoryInterface;
use App\Repositories\RecipientRepositoryInterface;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SpecialOfferController extends Controller
{
    /**
     * Recipient repository interface
     *
     * @var \App\Repositories\RecipientRepositoryInterface
     */
    private $recipient_repository;

    /**
     * Special Offer repository interface
     *
     * @var App\Repositories\SpecialOfferRepositoryInterface
     */
    private $special_offer_repository;

    /**
     * Class constructor
     *
     * @param SpecialOfferRepositoryInterface $special_offer_repository - Special Offer respository interface
     */
    public function __construct(
        RecipientRepositoryInterface $recipient_repository,
        SpecialOfferRepositoryInterface $special_offer_repository
    ) {
        // Middlewares
        $this->middleware('route.filters')->only(['index', 'show']);

        // Repositories interfaces
        $this->recipient_repository = $recipient_repository;
        $this->special_offer_repository = $special_offer_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $special_offers = $this->special_offer_repository->getAllPaginated($request->attributes->get('filters_array'));

        return view('special-offer.index', compact('special_offers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('special-offer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\SpecialOfferRequest    $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(SpecialOfferRequest $request)
    {
        $special_offer = $this->special_offer_repository->create(
            $request->name,
            $request->discount,
            Carbon::createFromFormat('Y-m-d', $request->validity)
        );

        return redirect()->route('special-offer.show', $special_offer->slug);
    }

    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $special_offer = $this->special_offer_repository->getBySlug($request->special_offer);
        $recipients = $this->recipient_repository->getAll($request->attributes->get('filters_array'));

        return view('special-offer.show', compact('special_offer', 'recipients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $special_offer = $this->special_offer_repository->getBySlug($request->special_offer);

        return view('special-offer.edit', compact('special_offer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\SpecialOfferRequest    $request
     * @param  integer                                  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(SpecialOfferRequest $request, $id)
    {
        $special_offer = $this->special_offer_repository->update(
            $id,
            $request->name,
            $request->discount,
            Carbon::createFromFormat('Y-m-d', $request->validity)
        );

        return redirect()->route('special-offer.show', $special_offer->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->special_offer_repository->delete($id);

        return redirect()->route('special-offer.index');
    }
}

resources/views/special-offer/create.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('special-offer.create') }}

  {{ Form::open(['route' => 'special-offer.store', 'method' => 'POST']) }}
    <div class="card">
      <div class="card-body">
        @include('special-offer.component.form')
      </div>
      <div class="card-footer text-right">
        {{ Form::bsSubmit('Create') }}
      </div>
    </div>
  {{ Form::close() }}

@endsection

resources/views/special-offer/edit.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('special-offer.edit', $special_offer) }}

  {{ Form::open(['route' => ['special-offer.update', $special_offer->id], 'method' => 'PUT']) }}
    <div class="card">
      <div class="card-body">
        @include('special-offer.component.form')
      </div>
      <div class="card-footer text-right">
        {{ Form::bsSubmit('Update') }}
      </div>
    </div>
  {{ Form::close() }}

@endsection

resources/views/special-offer/index.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('special-offer.index') }}

  @include('special-offer.component.filter')

  <div class="card">
    @include('special-offer.component.table')
  </div>


@endsection

resources/views/special-offer/show.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('special-offer.show', $special_offer) }}

  <div class="row">
    <div class="col-md-4">
      @include('special-offer.component.card')
    </div>
    <div class="col-md-8 mb-3">
      <div class="card">
        <h5 class="card-header">Recipients</h5>
        @include('recipient.component.table')
      </div>
    </div>
    <div class="col-md-8 offset-4">
      <div class="card">
        <div class="card-header"></div>
      </div>
    </div>
  </div>


@endsection

@include('components.modal.delete', ['action' => route('special-offer.destroy', $special_offer->id), 'modal_name' => 'deleteRecipient'])