routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Route::resource('recipient', 'RecipientController');
Route::resource('special-offer', 'SpecialOfferController');
Route::resource('voucher-code', 'VoucherCodeController')->only(['index', 'show']);
Route::get('voucher-code/{voucher_code}/redeem', 'VoucherCodeController@redeem')->name('voucher-code.redeem');
Route::post('voucher-code/{voucher_code}/redeem', 'VoucherCodeController@processRedeem')->name('voucher-code.redeem');

app/Recipient.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Recipient extends Model
{
    use Sluggable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ],
        ];
    }

    /**
     * Special Offer relation with Recipient model
     * @return \App\SpecialOffer
     */
    public function specialOffers(){
        return $this->belongsToMany(
            SpecialOffer::class,
            'voucher_codes',
            'recipient_id',
            'special_offer_id'
        );
    }

    /**
     * Apply E-mail filter in model
     *
     * @param  \Illuminate\Database\Eloquent\Builde $query
     * @param  string                               $email
     *
     * @return \Illuminate\Database\Eloquent\Builde
     */
    public function scopeFilterEmail($query, $email)
    {
        return $query->where('email', 'like', '%'.$email.'%');
    }

    /**
     * Apply Name filter in model
     *
     * @param  \Illuminate\Database\Eloquent\Builde $query
     * @param  string                               $name
     *
     * @return \Illuminate\Database\Eloquent\Builde
     */
    public function scopeFilterName($query, $name)
    {
        return $query->where('name', 'like', '%'.$name.'%');
    }


    /**
     * Apply Special offer filter in model
     *
     * @param  \Illuminate\Database\Eloquent\Builde $query
     * @param  string                               $name
     *
     * @return \Illuminate\Database\Eloquent\Builde
     */
    public function scopeFilterSpecialOffer($query, $slug)
    {
        return $query->whereHas('specialOffers', function ($special_offer) use ($slug) {
            $special_offer->whereSlug($slug);
        }) ;
    }
}

app/Http/Controllers/RecipientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RecipientCreateRequest;
use App\Http\Requests\RecipientUpdateRequest;
use App\Http\Resources\RecipientResource;
use App\Repositories\RecipientRepositoryInterface;
use App\Repositories\VoucherCodeRepositoryInterface;
use App\Repositories\SpecialOfferRepositoryInterface;
use Illuminate\Http\Request;

class RecipientController extends Controller
{
    /**
     * Recipient repository interface
     *
     * @var \App\Repositories\RecipientRepositoryInterface
     */
    private $recipient_repository;

    /**
     * Special Offer repository interface
     *
     * @var \App\Repositories\SpecialOfferRepositoryInterface
     */
    private $special_offer_repository;

    /**
     * Voucher Codes repository interface
     *
     * @var \App\Repositories\VoucherCodeRepositoryInterface
     */
    private $voucher_code_repository;

    /**
     * Class constructor
     *
     * @param \App\Repositories\RecipientRepositoryInterface    $recipient_repository       - Recipient repository interface
     * @param \App\Repositories\SpecialOfferRepositoryInterface $special_offer_repository   - Special Offer repository interface
     * @param \App\Repositories\VoucherCodeRepositoryInterface  $voucher_code_repository    - Voucher Code repository interface
     */
    public function __construct(
        RecipientRepositoryInterface $recipient_repository,
        SpecialOfferRepositoryInterface $special_offer_repository,
        VoucherCodeRepositoryInterface $voucher_code_repository
    ) {
        // Middlewares
        $this->middleware('route.filters')->only(['index']);

        // Repositories interfaces
        $this->recipient_repository     = $recipient_repository;
        $this->special_offer_repository = $special_offer_repository;
        $this->voucher_code_repository  = $voucher_code_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param \App\Http\Requests\RecipientCreateRequest  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $recipients = $this->recipient_repository->getAllPaginated($request->attributes->get('filters_array'));

        return view('recipient.index', compact('recipients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('recipient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\RecipientCreateRequest  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(RecipientCreateRequest $request)
    {
        $recipient = $this->recipient_repository->create(
            $request->name,
            $request->email
        );

        return redirect()->route('recipient.show', ['recipient' => $recipient->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $recipient      = $this->recipient_repository->getBySlug($request->recipient);
        $voucher_codes  = $this->voucher_code_repository->getLatestFromRecipient($recipient);
        $special_offers = $this->special_offer_repository->getLatestFromRecipient($recipient);

        return view('recipient.show', compact('recipient', 'voucher_codes', 'special_offers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $recipient = $this->recipient_repository->getBySlug($request->recipient);

        return view('recipient.edit', compact('recipient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\RecipientUpdateRequest  $request
     * @param  int                                       $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(RecipientUpdateRequest $request, $id)
    {
        $recipient = $this->recipient_repository->update($id, $request->name, $request->email);

        return redirect()->route('recipient.show', $recipient->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->recipient_repository->delete($id);

        return redirect()->route('recipient.index');
    }
}

resources/views/recipient/create.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('recipient.create') }}

  {{ Form::open(['route' => 'recipient.store', 'method' => 'POST']) }}
    <div class="card">
      <div class="card-body">
        @include('recipient.component.form')
      </div>
      <div class="card-footer text-right">
        {{ Form::bsSubmit('Create') }}
      </div>
    </div>
  {{ Form::close() }}

@endsection

resources/views/recipient/edit.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('recipient.edit', $recipient) }}

  {{ Form::open(['route' => ['recipient.update', $recipient->id], 'method' => 'PUT']) }}
    <div class="card">
      <div class="card-body">
        @include('recipient.component.form')
      </div>
      <div class="card-footer text-right">
        {{ Form::bsSubmit('Update') }}
      </div>
    </div>
  {{ Form::close() }}

@endsection

resources/views/recipient/index.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('recipient.index') }}

  <div class="row">
    <div class="col-12">
      @include('recipient.component.filter')
    </div>
  </div>

  <div class="card">

    @include('recipient.component.table')

  </div>


@endsection

resources/views/recipient/show.blade.php
@extends('layouts.app')

@section('content')

  {{ Breadcrumbs::render('recipient.show', $recipient) }}

  <div class="row">

    <div class="col-4">
      @component('recipient.component.card', ['recipient' => $recipient])
      @endcomponent
    </div>

    <div class="col-8">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Voucher Codes</h5>
        </div>
        @component('voucher-code.component.table', ['voucher_codes' => $voucher_codes])
        @endcomponent
      </div>
    </div>

    <div class="mt-3 col-8 offset-4">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Special Offers</h5>
        </div>
        @component('special-offer.component.table', ['special_offers' => $special_offers])
        @endcomponent
      </div>
    </div>
  </div>


@endsection

@include('components.modal.delete', ['action' => route('recipient.destroy', $recipient->id), 'modal_name' => 'deleteRecipient'])